### ISSUE TITLE
[feature request] option to use toast message for warning indicator

### ISSUE THREAD

**Issue by RalphORama** [gbl/DurabilityViewer#103]
The current visual warning style is very distinct but can cause the screen to rapidly flash if you're using, for example, an efficiency 5 pick on netherrack, which is hard on the eyes. 

It would be cool if there was an additional option to display a toast in the top right like vanilla Minecraft does for some types of notifications. 

I think a toast + warning sound would be much easier on the eyes during late nights tearing through netherrack and similar situations.

**Comment by gbl** [comment]
In the early days of DurabilityViewer, people kept complaining it didn't warn them in time. Which was largely because the sound wasn't loud and distinct enough, or beacuse the text in the lower center of the screen wasn't visible enough. So I changed both to something that you just can't miss if you have it turned on at all, and don't really want to change this. The intention is, after all, to make you stop doing what you're doing.
