### ISSUE TITLE
Compatability issue with voxel map? (Conflict with datapack)

### ISSUE THREAD

**Issue by ghost** [gbl/DurabilityViewer#15]
I will create a issue over on voxel maps github as well but it seems the 2 conflict with each other. Your mod works fine till voxel map is installed. What I am speaking of can be seen [Here](https://gyazo.com/13ae2c4885887aedde71da4de746e4ca) 

It seems to make your overlay keep flashing, except for the regeneration one seen [here](https://gyazo.com/a243cde177aa5eee9e2fb6d0dbf97c10) Not sure why that would be a thing?

How to reproduce? Have both mods installed.

I have tried going through settings on both mods and nothing seems to have fixed it. Would really like to see a fix for this because I love your mod and voxel map. Thank you for your time

-Derpingtonishere

**Comment by gbl** [comment]
Hm, I've been using VoxelMap with Durability Viewer for months, without ever seeing this issue. Which exact versions are you using, and are there any other mods installed?
Does this also happen when you turn the "Effect Duration" config option off?

**Comment by ghost** [comment]
Minecraft version:1.15.2

Mods List:
1. Better sleeping
2. Clear skies
3. Command macros
4. Custom selection box
5. giselbaers durability viewer
6. Infinity fix
7. Inventory profiles
8. Jump over fences
9. light overlay
10. Lithium
11. Logical zoom
12. Mod menu
13. shulker box tooltip
14. Tweakeroo
15. Voxel map

It also happens when effect duration is off in config.

I should add that all the other plugins were installed alongside of durability viewer for a couple of months and had no issue. I installed the latest version of voxel map yesterday and this is what it kept doing. That made me believe that it was a compatibility issue with your mod and voxel map but if you are using them as well with no issue then maybe it's another one conflicting with voxel  and causing yours to go haywire.

This is on a single player map and playing via lan server. The other person playing is seeing the same issue as well. Any other information I will be more than willing to help. 

Thanks again
-Derpington

**Comment by gbl** [comment]
I just created a new instance, downloaded the mods from your list (plus malilib plus the fabric api), and it seems to work well. However, tweakeroo (from https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files) makes my game crash on startup - where did yours come from?

These are the mods I'm currently using, all downloaded from CF in the newest versions:

bettersleeping-0.3.0.jar
clear-skies-mc115-1.1.19.jar
cmdkeybind-1.4.2.jar
CustomSelectionBox-4.1.0.jar
durabilityviewer-1.15.2-fabric0.4.23-1.7.jar
fabric-api-0.4.29+build.290-1.15.jar
fabricmod_VoxelMap-1.9.14_for_1.15.1.jar
Fence+Jumper-1.14.4-1.0.8.jar
infinityfix-1.1.0.jar
inventoryprofiles-fabric-1.15-0.1.0-dev.6.jar
LightOverlay-4.2.jar
lithium-mc1.15.2-fabric-0.3.1.jar
logical_zoom-0.0.2.jar
malilib-fabric-1.15.2-0.10.0-dev.20+arne.2.jar
mamiyaotaru
modmenu-1.10.1+build.30.jar
shulkerboxtooltip-1.4.5+1.15.jar


and this is what it's looking like:

![image](https://user-images.githubusercontent.com/243563/74132520-09abbd00-4be7-11ea-8c1e-b43257a2be10.png)

as you see all icons still display when the duration is at 14.

Another thing you might try: open the inventory, make sure the craft book is closed so you see the effects to the left of the inventory - do they show all the time, or do they disappear as well? If so, it seems like something is cancelling your effects instead of it just being a display bug.

**Comment by ghost** [comment]
I checked what my friend also had installed and I seen that he had a data pack installed called "Bigger beacon radius" and that seems to be the culprit. I am truly sorry for the inconvenience as I should have checked data packs. Thank you for the help you gave me and hope you continue with these mods. You do a great job at making them and are quick to respond to my question (even if it wasn't your mods issue) Just seemed like it was an issue with your mod and voxel because it didn't do this until I installed voxel. Again thank you for taking your time to help me. I guess in the future if someone is having an issue maybe the culprit may be a datapack. I will mark this as closed.
