### ISSUE TITLE
Timer stopped working?

### ISSUE THREAD

**Issue by ghost** [gbl/DurabilityViewer#16]
The countdown timer for the statuses have stopped working. I am unsure of when they disappeared because I had them off for a while but upon turning them back on they don't count down anymore, Just sit there like the countdown is off as seen [here](https://gyazo.com/adda9fe8603f211c3453971f02f21230) but the setting is on in the configs as seen [here](https://gyazo.com/71a0e5a1695f5f6a04ea4281eaf224f3) my friend also is having the same issue but he never turned it off and he said the only thing he can think of is we have 2 new mods installed 1 being Optifabric and the other Optifine which we both have installed. I am unsure if those are what is causing it though. And yes this time I checked to make sure he didn't have any data packs this time and he has none. I guess my question is, is their something in Optifine that would affect the countdown timer? If so what is it.

**Comment by gbl** [comment]
Which exact version of Optifine and Optifabric are you using?

I just created an instance with nothing but fabric, optifabric, optifine, and durabilityviewer, all in their newest versions:

-rw-rw-r-- 1 gbl gbl   79724 Feb 20 15:03 durabilityviewer-1.15.2-fabric0.4.23-1.7.jar
-rw-rw-r-- 1 gbl gbl  500234 Feb 20 15:03 fabric-api-0.4.20+build.273-1.15.jar
-rw-rw-r-- 1 gbl gbl  314652 Feb 20 15:02 optifabric-1.0.0-beta4.jar
-rw-rw-r-- 1 gbl gbl 5388876 Feb 20 15:03 preview_OptiFine_1.15.2_HD_U_G1_pre5.jar

and this is the result:

http://i.imgur.com/WdeIFNI.png

http://i.imgur.com/lEDQtrq.png  -- yes Optifine is loaded, see row 5.

Are you, possibly, in creative mode? Because neither the armor / tool things nor stat effect durations are shown in creative mode, as they don't make much sense there.

**Comment by ghost** [comment]
Very sorry for the slow reply, really busy day. So oddly even after redownloading optifacric, optifine, and durability viewer yesterday and trying to make sure it wasn't a corrupt install it didn't work, even my friends didn't work after doing it. Even tried it in a single player with the same affect (set to survival as well) I then tried it again today to see what would happen and it fixed it, fixed my friends as well. Really not sure what is going on here but if it happens again I will let you know but as for now I guess this is closed.

For reference I was using all the same versions you are.

And again I am really sorry for wasting your time. 1.15 has been a rough version for me for some reason. Things working then not working but somehow seem to fix themselves mysteriously. I think it may be time for maybe a refresh of minecraft in general and starting from scratch to see if some of my issues stop happening.
