### ISSUE TITLE
There is no option to

### ISSUE THREAD

**Issue by ghost** [gbl/DurabilityViewer#19]
I just wanted to have a durability count when I hover over an item at all time even when full hp but I have to damage first

and the hud I cannot disable and the braking sound, can you please fix that, I am on snapshot 20w13b

**Comment by gbl** [comment]
There's no way to disable the hud; showing the hud is the main point of the mod. If you just want an item tooltip, press F3-H.
To see the durability of the item all the time (instead of the damage), set the "Percent to show damage" option to 100.
The CurseForge page of the mod explains how to have the sound at lower durabilities only, or disable it completely.
