### ISSUE TITLE
Conflict with Dynamic Surroundings: HUD

### ISSUE THREAD

**Issue by opaillya** [gbl/DurabilityViewer#2]
When Dynamic Surroundings: HUD has the option to modify status effects turned on, Durability Viewer disappears. The issue seems to be the two mods both trying to interact with the vanilla status effect icon.  I want Dynamic Surroundings's status effect modification, but the durability HUD from Durability Viewer. I feel like this would be easier to solve on the side of Durability Viewer, maybe by adding a config to not interact with status effects?

**Comment by gbl** [comment]
Just a short question: are you using 1.12.2, the only version I could find  Dynamic Surroundings: HUD for, or 1.13.2 ?

**Comment by gbl** [comment]
Ok, I investigated into it, and the problem seems to be that Dynamic Surroundings: HUD registers itself with high priority, and tries to tell Minecraft not to render the standard potion HUD. But because it sets its own priority to HIGH, it also stops all other mods from doing their rendering. Since MC doesn't have a "render durabiliy overlay event", I had to attach my rendering to something, and I chose potion effects rendering for that, because I'm hooking into this anyway.

Of course I could move the durability rendering to something else, but that'd just move the problem to the next mod that also tries to modify the "something else" thing.

I opened an issue with Dynamic Surroundings here: https://github.com/OreCruncher/DynamicSurroundingsHuds/issues/7 , and I hope OreCruncher will set his own priority to LOW in the future, at least when it comes to cancelling the render.

When he does that, you can use the "Effect Duration" config in DurabilityViewer to turn off my Effect Duration rendering, which would be shown in the original position where, ofc, you don't want it anymore with Dynamic Surroundings: HUD enabled.

**Comment by IdrisQe** [comment]
Hi so not sure why nobody else has said anything but this actually still seems to be an issue.

With version 1.12 1.6 of this mod and version 3.6.0.0 of DS HUD (the version that fixed this issue on their end) as well as version 3.6.2.1 of Dynamic Surroundings itself, this issue still occurs. If the DS Potion HUD is set to be visible, it completely disables Durability Viewer from rendering, regardles of settings.

Figure I'll report this on both pages even tho I doubt 1.12 is going to be supported anymore.
