### ISSUE TITLE
[Improvment] Show TR Tool charge

### ISSUE THREAD

**Issue by KnatteAnka** [gbl/DurabilityViewer#36]
would be great if this was able to show current charge och held tool from TechReborn (1.16 Fabric)

**Comment by gbl** [comment]
Sorry, I never played TR, and just downloaded it and read about it in the wiki.
You're talking about the tools like chainsaw, jackhammer, etc., right?
And those don't have normal durability, so there's nothing to display for them, normally, as I see it? So we could have the energy level instead of the durability, for them?

**Comment by gbl** [comment]
I posted a version 1.8.0 to CF which should work with TechReborn, as far as I can tell. Please give me feedback about this.

**Comment by KnatteAnka** [comment]
Works like a charm 👍  😃  good job.
