### ISSUE TITLE
Crash on Editing Mod Config

### ISSUE THREAD

**Issue by JoshMayberry** [gbl/DurabilityViewer#40]
On the latest version (1.8.1), the game crashes when I try changing the configin-game.
I have attached the crash log.
[crash-2020-08-22_19.40.05-client.txt](https://github.com/gbl/DurabilityViewer/files/5113269/crash-2020-08-22_19.40.05-client.txt)

**Comment by gbl** [comment]
This is most probably because several of my mods (in your case, beenfo, durabilityviewer, and grid), share the same library, and grid is already updated to 1.16.2-pre1, so durabilityviewer uses that version of the config screen, which won't work with 1.16.1. 
Can you try replacing Grid with the 1.16.1 version at https://www.curseforge.com/minecraft/mc-mods/grid/files/3038548, then check if it works?

**Comment by JoshMayberry** [comment]
Sure thing!
(You do great work btw)

Down-grading grid worked.
The config screen looks a bit weird (no scroll bar to get to the options below the screen)- but it does not crash anymore.
![image](https://user-images.githubusercontent.com/11482252/90983153-ebc9f800-e539-11ea-882c-f44e54e079da.png)
