### ISSUE TITLE
1.17 Fabric crash on AOF4 0.0.1

### ISSUE THREAD

**Issue by triphora** [gbl/DurabilityViewer#58]
Hiya!
I was playing AOF4 0.0.1 to test it out, and added a few other mods on top. One of those mods on top was durability viewer.
The crash log I got from it cited durability viewer and something to do with Trinkets compatibility: https://paste.ee/p/kJEKz
I was unable to reproduce the crash with only durability viewer, Trinkets, and FAPI, though.
I was able to launch the game successfully when turning off durability viewer: https://paste.ee/p/jc1hS
I'm using `durabilityviewer-1.17-fabric0.34.9-1.10.jar` right from Modrinth.
If you need me to get another crash report (e,g. with Mixin Trace), I'd be happy to provide it.
Thanks for your work on this mod :)

**Comment by gbl** [comment]
Hey Emma,
Trinkets was rewritten completely with 3.0.0, so my old method of detecting it doesn't work anymore, which causes the crash.
(This also means if you use DV 1.10 and Trinkets 3 and nothing else, it should crash!).

I made a beta version, but no guarantees, as there aren't many actual trinkets yet.
Please check out https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer/files/3346784 and tell me if it works for you!

Or try it from Modrinth; I didn't publish it there at first because I wanted to collect feedback from the first person who reported the bug first, then never caught up. It's at https://modrinth.com/mod/durabilityviewer/version/J80q62Gq now.

**Comment by triphora** [comment]
I got a crash initially when joining a server (https://paste.ee/p/10uai), but I seem to no longer be getting it after starting the game up again, so this is resolved. Thanks again!
