### ISSUE TITLE
[Request] 1.19.4 Support

### ISSUE THREAD

**Issue by toydotgame** [gbl/DurabilityViewer#83]
No-one else has reported on the errors with 1.19.4 yet (probably because version bump Issues are annoying asf), so I thought I'd try to give some detail on whatever's broken.

[Full dump here.](https://pastebin.com/raw/MTjUQs8i) (I had a bunch of other mods loaded too but the specific fatal error in that log was from Durability Viewer) The base error is this:
```
java.lang.NoSuchMethodError: 'void net.minecraft.class_918.method_4010(net.minecraft.class_1799, int, int)'
	at de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability.renderItems(GuiItemDurability.java:380)
	at de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability.onRenderGameOverlayPost(GuiItemDurability.java:300)
	at net.minecraft.class_329.handler$zbg000$durabilityviewer$beforeRenderDebugScreen(class_329.java:3407)
	at net.minecraft.class_329.method_1753(class_329.java:264)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
```
…so, an error at this line?
https://github.com/gbl/DurabilityViewer/blob/7ab14d31a44476de0e0512702031fb4238e0ded0/src/main/java/de/guntram/mcmod/durabilityviewer/client/gui/GuiItemDurability.java#L380
<br>
1.19.4 is a trainwreck of an update for modding. Most of my 1.19.3 mods caused outright crashes of the game either on the main menu load or on the world render. Most of these issues are `java.lang.NoSuchMethodError`s, which I'm not sure on how to fix in code. They always have at least something to do with rendering at some point along the way.

### Other Details:
**Minecraft Version:** 1.19.4
**Loader:** Fabric 0.14.18
**Durability Viewer Version:** `1.19.3-fabric0.68.1-1.10.3` (built off branch `fabric_1_19` I assume)
**OS:** Arch Linux 6.2.7-arch1-1

<details>
    <summary>PS</summary>

###### I apologise for making a version bump issue. I've developed Spigot plugins in the past and version bump Issues are always the most annoying ones. Sorry.
</details>

**Comment by giorov** [comment]
same

**Comment by wilebaldo** [comment]
Until I know, the mod must to be rebuild for the specific minecraft version also if is a minor updale like the 1.19.3 to 1.19.4.

I try same as you, just use the mod for the 1.19.3 on the 1.19.4 and I have problems may times is not allow even to open the minecraft, the game crash.

and also I read in another comment, the developer for this mod is not updating anymore, he said is not playing minecraft since 1.16 so he said is not time to do it for the mod. I'm talking with a friend like he have more experience developing software with java, but he is a little be busy, so I try to update the mod, but like I'm not expert I try the best I cant, still not any working version jet.
