### ISSUE TITLE
Mod Menu: Failed to load Durability Viewer settings

### ISSUE THREAD

**Issue by icynstant** [gbl/DurabilityViewer#87]
"Failed to load Durability Viewer settings. Report to DV author, not Mod Menu"
![2023-06-28_21 23 13](https://github.com/gbl/DurabilityViewer/assets/127024748/35230af6-34a8-4e82-a355-5919c3e80e7f)

Fabric 1.20.1

No problems with my other 70 mods

**Comment by gbl** [comment]
Yep. Same as #86. Will fix in the next hours.

**Comment by icynstant** [comment]
> Yep. Same as #86. Will fix in the next hours.

Thank you, don't rush yourself. Will it work fine if i'll change text file?

Btw im shocked how fast was answer

**Comment by gbl** [comment]
I was already working on it, thus the fast answer. I messed up and included the wrong (old) version of the config library in all the mods, which is why all of them aren't working.

Changing the text file won't work, but dropping the jar file from https://github.com/gbl/GBfabrictools/releases/tag/1.4 into your mods folder should.
