### ISSUE TITLE
Game crash on startup with 1.20.1

### ISSUE THREAD

**Issue by xenouch** [gbl/DurabilityViewer#93]
Hello

Same probleme as [#88](https://github.com/gbl/DurabilityViewer/issues/88)

Already installed "cloth config" from [https://modrinth.com/mod/cloth-config](https://github.com/gbl/DurabilityViewer/issues/url)

Using Fabric Loader version, v0.14.21
Using Fabric API version, fabric-api-0.85.0+1.20.1.jar
I try with fabric-api-0.83.0+1.20.1.jar with same result

[crash-2023-07-05_08.13.14-client.txt](https://github.com/gbl/DurabilityViewer/files/11954457/crash-2023-07-05_08.13.14-client.txt)

Thanks for your work :)

**Comment by gbl** [comment]
Which version of cloth config did you install?

DurabilityViewer needs at least 11.0.99.

The cloth config in your system comes from BetterF3 which has cloth config 11.0.98. So I assume that

a) You didn't put cloth config into the correct folder
b) The jar you installed is an older version, which causes the 11.0.98 from BetterF3 to be used, which is still not new enough
c) BetterF3 wants "exactly 11.0.98" instead of "something newer than 11.0.98", which prevents the 11.0.99 from loading

Please double check if you installed cloth config 11.0.99 correctly, and if you did, try disabling BetterF3.

**Comment by xenouch** [comment]
My bad i'm a moron i downlaad the version 1.16.4 of cloth config...

Thanks for your support :)
